-- AlterTable
ALTER TABLE "Post" ADD COLUMN     "qtyComments" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "qtyLikes" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "qtyRetweets" INTEGER NOT NULL DEFAULT 0;
